### ISSUE TITLE
Spacing Discussion 1

### ISSUE THREAD

**Issue by as43z** [humans4u/DesignGuidelines#5]
This is the space for spacing discussion.

I suggest the addition of spacers and spacing values to the design guidelines. According to [1] there is a rule in the designing world of UI/UX to work in 4px grid (or 8px depending on the case), and work in increments of 4px.

May I suggest the creating of spacing values as well as the creation of _spacers_ for UI.

Would prefer to declare the spacings as `:root` elements. 
```css
:root {
  /* Minimum spacing grid value */
  --minimum-spacing: 4px;
  /*
  --factor-two-spacing:   calc( var(--minimum-spacing) * 2 ); = 8px
  --factor-three-spacing: calc( var(--minimum-spacing) * 3 ); = 12px
  ... Until make sense (32px??)
  */
}
```

For the spacers could work with the definition of:
```css
.spacer-32px {
   height: var(--factor-eight-spacing);
}
/* ... */
```

Pinging members @danigarfe @MaFe1401 @Angelfm98 @errezeeta @WillyAguilaPalleja 

[1] [https://www.thedesignership.com/blog/the-ultimate-spacing-guide-for-ui-designers](https://www.thedesignership.com/blog/the-ultimate-spacing-guide-for-ui-designers)
